class_name CharacterAnimator
extends AnimatedSprite2D
# owns: switching between the "idle" and "walk" SpriteFrames animations based on movement
#   state. down-facing only for now, since only a camera-facing pose exists per character
#   (see testing/todos.md F-026); every frame plays regardless of which way facing points.
# does not own: movement itself (PlayerController), or frame timing/pixels (the SpriteFrames
#   resource assigned in the editor, generated by design-export/src/mon-art.js's
#   characterAnimFrames()).

@export var controller: Node

func _ready() -> void:
	if controller == null:
		controller = get_parent().get_parent()

func _process(_delta: float) -> void:
	if controller == null or not controller.has_method("is_moving"):
		return
	var target_animation: StringName = &"walk" if controller.is_moving() else &"idle"
	if animation != target_animation:
		play(target_animation)
